import type { Metadata } from "next";
import { Geist, Geist_Mono, Quantico, SUSE } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const quantico = Quantico({
  subsets: ["latin"],
  weight: ["400", "700"],
  style: ["normal", "italic"],
  variable: "--font-quantico",
  display: "swap",
}); 

const suse = SUSE({
  subsets: ["latin"],
  weight: ["400", "700"],
  style: ["normal"],
  variable: "--font-suse-mono",
  display: "swap",
});

export const mertadata: Metadata = {
  title: "Novellina Edyawati - Portfolio",
  description: "Welcome to my portfolio website! I'm Novellina Edyawati, a passionate Data Scientist and Software Engineer. Explore my projects, skills, and experience in transforming data into actionable insights and building impactful solutions."
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${quantico.variable} ${suse.variable}`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-primary text-secondary `}
      >
        {children}
      </body>
    </html>
  );
}
